services:
  user-nginx:
    build:
      context: ..
      dockerfile: .docker/nginx/Dockerfile
      args:
        STAGE: user
    ports:
      - "${APP_PORT:-127.0.0.1:80}:80"
    volumes:
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
    depends_on:
      - user-api
    environment:
      - API_SERVICE_NAME=user-api
    networks:
      - user

  user-api:
    build:
      context: ..
      dockerfile: .docker/php/Dockerfile
      args:
        APP_ENV: "${APP_ENV}"
        STAGE: user
    volumes:
      - .:/var/www/html
    depends_on:
      - user-mysql
    networks:
      - user

  user-mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: '${USERS_DB_DATABASE}'
      MYSQL_USER: '${USERS_DB_USERNAME}'
      MYSQL_PASSWORD: '${USERS_DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${USERS_DB_PASSWORD}'
    volumes:
      - 'user-mysql-data:/var/lib/mysql'
      - 'user-mysql-logs:/var/log/mysql'
    networks:
      - user

  user-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - user-mysql
    ports:
      - '${PHPMYADMIN_PORT:-127.0.0.1:8081}:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: user-mysql
      PMA_USER: '${USERS_DB_USERNAME}'
      PMA_PASSWORD: '${USERS_DB_PASSWORD}'
    depends_on:
      - user-mysql
    networks:
      - user

volumes:
  user-mysql-data:
  user-mysql-logs:
networks:
  user: {}