name: CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  push:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/application
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: secret
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install dependencies
        run: composer install
        
      - name: Install Frontend dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Copy environment file
        run: cp .env.example .env
      - name: Update Laravel .env
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ env.MYSQL_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ env.MYSQL_USER }}" >> .env
          echo "DB_PASSWORD=${{ env.MYSQL_PASSWORD }}" >> .env

      - name: Generate application key
        run: php artisan key:generate

      #- name: Run database migrations
        #run: php artisan migrate

      - name: Validate Format code
        run: ./vendor/bin/pint

  deploy:
    needs: push
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd andrevk9.beget.tech/public_html
            git reset --hard HEAD  
            git clean -df
            git pull origin main
            ls