name: Deployment UserService

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/user
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install composer packages
        run: |
          php -v
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: 'Compress composer folder'
        run: tar -czvf composer.tgz vendor/

      - name: Upload composer assets
        uses: actions/upload-artifact@v4
        with:
          name: composer
          path: ./backend/user/composer.tgz
          retention-days: 3
          if-no-files-found: error

  npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/user
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: npm install
        run: |
          npm --version
          npm install
      - name: 'Compress node_modules folder'
        run: tar -czvf node_modules.tgz node_modules/

      - name: Upload node_modules assets
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: ./backend/user/node_modules.tgz
          retention-days: 3
          if-no-files-found: error

  build_assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/user
    needs: [composer, npm]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download npm artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Unpack artifacts
        run: |
          tar xvfz ./backend/user/node_modules.tgz
      - name: npm install
        run: |
          npm --version
          npm run production
      - name: 'Compress public folder'
        run: tar -czvf public.tgz public/

      - name: Upload public assets
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public.tgz
          retention-days: 3
