name: Deployment UserService

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/user
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install composer packages
        run: |
          php -v
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: 'Compress composer folder'
        run: tar -czvf composer.tgz vendor/

      - name: Upload composer assets
        uses: actions/upload-artifact@v4
        with:
          name: composer
          path: ./backend/user/composer.tgz
          retention-days: 3
          if-no-files-found: error

  build_assets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/user
    needs: [composer]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download composer  artifacts
        uses: actions/download-artifact@v4
        with:
          name: composer 
          path: ./backend/user/composer.tgz

      - name: Unpack artifacts
        run: |
          tar xvfz composer.tgz
          ls

      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          source: "test.tar"
          script: |
            cd www/u181705.test-handyhost.ru/teacher
            git reset --hard HEAD  
            git clean -df
            git pull origin main
            cd backend/user
            chmod -R 777 storage bootstrap/cache
            cp .env.example .env
