name: CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  composer:
    name: Composer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/user
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install composer packages
        run: |
          php -v
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: 'Compress composer folder'
        run: tar -czvf composer.tgz vendor/

      - name: Upload composer assets
        uses: actions/upload-artifact@v2
        with:
          name: composer
          path: composer.tgz
          retention-days: 3

  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: npm install
        run: |
          npm --version
          npm install
      - name: 'Compress node_modules folder'
        run: tar -czvf node_modules.tgz node_modules/

      - name: Upload node_modules assets
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.tgz
          retention-days: 3

  build_assets:
    runs-on: ubuntu-latest
    needs: [composer, npm]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download npm artifacts
        uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: Unpack artifacts
        run: |
          tar xvfz node_modules.tgz
      - name: npm install
        run: |
          npm --version
          npm run production
      - name: 'Compress public folder'
        run: tar -czvf public.tgz public/

      - name: Upload public assets
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public.tgz
          retention-days: 3

  deploy:
    needs: ['build_assets']
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd andrevk9.beget.tech/public_html
            git reset --hard HEAD  
            git clean -df
            git pull origin main
            cd backend/user
            cp .env.example .env
            cat .env
            chmod -R 777 storage bootstrap/cache
            php artisan key:generate
            ls